/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#060e20",
        "tertiary": "#f2f3ff",
        "on-error-container": "#ffa8a3",
        "error-dim": "#d7383b",
        "on-secondary-container": "#d9c8ff",
        "on-secondary": "#280067",
        "secondary-fixed": "#dac9ff",
        "primary-fixed": "#00f5f5",
        "primary-dim": "#00e6e6",
        "primary-fixed-dim": "#00e6e6",
        "primary-container": "#00ffff",
        "secondary-container": "#5516be",
        "on-tertiary-fixed": "#394155",
        "secondary-dim": "#8455ef",
        "error": "#ff716c",
        "background": "#060e20",
        "on-tertiary": "#545b71",
        "on-surface-variant": "#a3abc3",
        "on-primary-fixed-variant": "#006262",
        "error-container": "#9f0519",
        "outline-variant": "#40485c",
        "surface-container": "#0f192f",
        "on-primary-container": "#005d5d",
        "surface-container-low": "#091327",
        "surface-container-lowest": "#000000",
        "on-background": "#dde5ff",
        "tertiary-fixed-dim": "#cfd7f0",
        "on-error": "#490006",
        "on-primary": "#006767",
        "inverse-surface": "#faf8ff",
        "on-primary-fixed": "#004343",
        "surface-bright": "#1f2b48",
        "secondary": "#ac8aff",
        "on-secondary-fixed-variant": "#5f28c8",
        "on-surface": "#dde5ff",
        "secondary-fixed-dim": "#ceb9ff",
        "tertiary-fixed": "#dde5ff",
        "tertiary-dim": "#cfd7f0",
        "surface": "#060e20",
        "on-tertiary-fixed-variant": "#555d72",
        "surface-container-high": "#141f37",
        "surface-tint": "#c1fffe",
        "outline": "#6d758b",
        "on-secondary-fixed": "#40009b",
        "surface-container-highest": "#19253f",
        "primary": "#c1fffe",
        "inverse-on-surface": "#4d556a",
        "on-tertiary-container": "#4b5368",
        "surface-variant": "#19253f",
        "inverse-primary": "#006a6a",
        "tertiary-container": "#dde5ff"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
  ],
}
